### ISSUE TITLE
readme file update

### ISSUE THREAD

**Issue by SalahudinMalik** [SalahudinMalik/Read-Excel-File#1]
please update the readme file and add some better documentation.

**Comment by pavluchenko** [comment]
Hi, please assign this issue to me and give a brief description of your requirement.

**Comment by SalahudinMalik** [comment]
@pavluchenko just follow this program and add proper documentation for that so the user can use it easily

**Comment by shubhamnarkhede** [comment]
Can you assign me this issue.
